FROM centos:7

# äJî≠ÉcÅ[Éã
RUN yum -y groupinstall "development tools" && \
yum -y install libpng-devel libtiff-devel libjpeg-devel && \
yum -y install centos-release-scl && \
yum -y install devtoolset-7-gcc-c++ && \
source /opt/rh/devtoolset-7/enable && \
yum -y install wget && \
cd /usr/src/ && \
wget http://ftpmirror.gnu.org/autoconf-archive/autoconf-archive-2019.01.06.tar.xz && \
tar xvvfJ autoconf-archive-2019.01.06.tar.xz && \
cd autoconf-archive-2019.01.06/ && \
./configure --prefix=/usr && \
make && \
make install && \
cd /usr/src/ && \
wget http://leptonica.org/source/leptonica-1.78.0.tar.gz && \
tar xvvfz leptonica-1.78.0.tar.gz && \
cd leptonica-1.78.0/ && \
./configure --prefix=/usr/local/ && \
make && \
make install && \
cd /usr/src/ && \
wget https://github.com/tesseract-ocr/tesseract/archive/4.1.1-rc2.tar.gz && \
tar xvvfz 4.1.1-rc2.tar.gz && \
cd tesseract-4.1.1-rc2 && \
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig && \
./autogen.sh && \
./configure --prefix=/usr/local/ --with-extra-libraries=/usr/local/lib/ --disable-openmp && \
make install 
